### ISSUE TITLE
Multiverse is invalid command

### ISSUE THREAD

**Issue by xMuratY** [LegitSoulja/OgarConsole#12]
Multiverse command return ;

Invalid Command!. Try 'help' for a list of commands

thanks

**Comment by LegitSoulja** [comment]
@xMuratY are you using the ogarconsole plugin?

**Comment by xMuratY** [comment]
yes

**Comment by Andrews54757** [comment]
multverse and exit is not available for plugins. YET

**Comment by LegitSoulja** [comment]
@xMuratY /\
