### ISSUE TITLE
password!

### ISSUE THREAD

**Issue by David1ali12** [LegitSoulja/OgarConsole#13]
hello that was what I was looking for all the time Ogarconsole when I make password = 1 
and I go to console I enter the password put it keeps asking for password 
why not make a login to will be better like user and pass then will get connect to console 
THX @LegitSoulja  damn Ogarconsole is amazing :smile:

**Comment by LegitSoulja** [comment]
Passwords cannot be less than 5 char less, nor 15 char long.

requirePassword enables and disable password usage, and password is the password.

**Comment by LegitSoulja** [comment]
If you are using the old versions of OgarConsole I don't know if they work still or not, and needs updating :/

**Comment by David1ali12** [comment]
ye I used ogarconsole123 but did not worked I turn it off

**Comment by LegitSoulja** [comment]
Your using the old version correct?

**Comment by LegitSoulja** [comment]
I'll update OgarConsole one last time

**Comment by David1ali12** [comment]
ok lol thank you
