### ISSUE TITLE
What ever I do keeps asking for password!

### ISSUE THREAD

**Issue by David1ali12** [LegitSoulja/OgarConsole#14]
hey @LegitSoulja  did I do anything wrong or its with plugin ?
password is :
 OgarConsole123
I enter -password [OgarConsole123]
in string or in out string it says :Invalid password. Please try again!.
![console](https://cloud.githubusercontent.com/assets/17472593/15707197/18a14816-2800-11e6-9ca9-f03968db1a57.PNG)
btw I added a better style once I finish I will pull request it :)

**Comment by David1ali12** [comment]
NVM I did not know that I shouldn't use [] ,

**Comment by LegitSoulja** [comment]
Lol
